### ISSUE TITLE
Add ability to use a specific interface regardless of the Provider

### ISSUE THREAD

**Issue by mohsenrezaeithe** [favonia/cloudflare-ddns#1006]
There are scenarios where, for example, the Docker container running the updater cannot be attached to a specific interface in the host, leaving the chosen Provider to use the "default" interface provided by the host host.

IIUC, today there's no configuration that tells a Provider to use a specific interface name. If not, is this a feature that'd be of interest to adding to the repo?

An example using trace, e.g. `cloudflare.trace:https://whatsmyip:eth0`

**Comment by favonia** [comment]
@mohsenrezaeithe Thanks for the suggestion. The main difficulty here is that Linux network routing does not natively support such an approach. Linux routing decides which interface to use based on IP addresses and other hints, rather than the other way around. It consults the routing table to determine the path, not the IP addresses of individual network interfaces. So, you would essentially have to manipulate the routing table to simulate the desired kernel behavior. In other words, the Linux network API does not allow you to directly specify the interface for each connection.

That said, perhaps someone has come up with a clever workaround for all of these limitations. Are you aware of a similar service or tool that allows you to specify the network interface when connecting to a remote server?

**Comment by mohsenrezaeithe** [comment]
According to the golang HTTP client documentation using a `net.Dialer` binding to an existing interface should be doable, but I wasn't able to successfully achieve this using the native `host` or `bridge` Docker networks.

At a high level, this is what the dialer would look like:

```go
// Specify the network interface to bind, e.g., "eth0".
	interfaceName := "eth0"

	// Create a custom transport with a dialer that binds to the specified interface.
	transport := &http.Transport{
		DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			d := &net.Dialer{
				Timeout:   10 * time.Second,
				KeepAlive: 10 * time.Second,
				Control: func(network, address string, rawConn syscall.RawConn) error {
					var controlErr error
					if err := rawConn.Control(func(fd uintptr) {
						// Bind the socket to the specified interface
						controlErr = syscall.SetsockoptString(int(fd), syscall.SOL_SOCKET, 25, interfaceName)
					}); err != nil {
					    return err
					}
					return controlErr
				},
			}
			return d.DialContext(ctx, network, addr)
		},
	}

        c := retryablehttp.NewClient()
	c.HTTPClient = SharedSplitClient(ipNet)
        client.HTTPClient.Transport = transport
```

However, this can be imitated using the Docker networks, when running as a Docker container, by creating and assigning an additional network to the Docker container:

```shell
docker network create
    -d macvlan
    -o parent=eth0
    --subnet=192.168.1.0/24
    --gateway=192.168.1.1
    --ip-range=192.168.1.128/25
    LAN0
```

and assigning this to the container:

```yaml
services:
  cloudflare-ddns:
...
    networks:
      LAN0:
...
networks:
  LAN0:
    external: true
    name: LAN0

```

**Comment by favonia** [comment]
@mohsenrezaeithe Thanks for the code. I apologize for my ignorance; I was unaware that someone had already implemented `SO_BINDTODEVICE`, which forces the kernel to ignore all routes not associated with a particular interface. This is what one would have to implement manually for the suggested feature. Because it's a routing table hack, it probably only works for IP, but perhaps that's good enough.

There seem to be two major drawbacks to using `SO_BINDTODEVICE`, though:
1.  The current codebase should run on all platforms Go can run. Relying on `SO_BINDTODEVICE` will certainly reduce portability.
2.  It seems `SO_BINDTODEVICE` requires superuser privileges.

I am curious about this comment:

> However, this can be imitated using Docker networks, when running as a Docker container, by creating and assigning an additional network to the Docker container.

If so, what is the downside of just using macvlan? As far as I can see, it has very little overhead.

**Comment by mohsenrezaeithe** [comment]
I wouldn't consider it a downside other than the fact that it becomes a supplemental step to running the updater, when interface binding is required. Much like required iptable routes in stricter networks.

There shouldn't be any noticeable overhead at runtime.

**Comment by favonia** [comment]
@mohsenrezaeithe I'm currently leaning towards not including anything that requires superuser privileges. However, I think these tips can be added to the README file. I wonder if you are fine with this. I'm worried about the cases where "the Docker container running the updater cannot be attached to a specific interface in the host" as you mentioned.

**Comment by mohsenrezaeithe** [comment]
I agree. I've gone ahead and added steps to achieve this with a Docker network for the time being. Depending where the interest lies, it can be updated in the future.

**Comment by favonia** [comment]
Updates: now we have a section for all special setups, including this one!

**Comment by favonia** [comment]
@mohsenrezaeithe More updates: the README instructions now use the newer `ipvlan`.
