### ISSUE TITLE
direct Mac binary?

### ISSUE THREAD

**Issue by symgryph** [favonia/cloudflare-ddns#142]
any way to get it to build on osx? 

```ini
kernel.org/pub/linux/libs/security/libcap/cap
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/syscalls.go:16:10: undefined: psx.Syscall3
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/syscalls.go:17:10: undefined: psx.Syscall6
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:229:29: undefined: syscall.SYS_PRCTL
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:241:29: undefined: syscall.SYS_PRCTL
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:253:29: undefined: syscall.SYS_PRCTL
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:266:29: undefined: syscall.SYS_PRCTL
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:279:22: undefined: syscall.SYS_CAPGET
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:346:37: undefined: syscall.SYS_CAPGET
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/cap.go:366:29: undefined: syscall.SYS_CAPSET
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/convenience.go:277:25: undefined: sysSetGroupsVariant
../../go/pkg/mod/kernel.org/pub/linux/libs/security/libcap/cap@v1.2.63/convenience.go:277:25: too many errors
bash-5.1$
```

**Comment by favonia** [comment]
I don't have access to macOS and I could not compile it using GitHub Actions (#143). However, the error messages seem to be different---what you showed here is the lack of certain symbols, while on GitHub it's the `cgo` not being used. I wonder if you have more insights on this?

**Comment by favonia** [comment]
I am closing this because I have not found a portable way to implement the dropping of capabilities (sometimes called "privileges" in other operation systems). The alternative is to implement proper security protections for different operating systems, but I would not have enough time to check the correctness of them (even if just for macOS). I am aware of the overhead and extra steps in using Docker in macOS (currently via xhyve), but that seems to be the easiest way to enforce a strong security protection. I want to maintain the property that, even when the updater is exploited to run arbitrary code, unless the Docker protection and other shields are simultaneously broken, only the DNS records can be modified in the worst case scenario.

**Comment by symgryph** [comment]
I could help you write a seccomp profile which you could put into the docker file. Additionally you could also run in rootless mode, which would greatly limit the attack surface even if docker were compromised. A microVM would also be another option. You might want to look at appainer which is a different model for deploying containers. It used to be called singularity. And of course there's just a dumb option of running as a non-privileged user with a different high number that will probably not conflict with local system user IDs.

Sincerely

Thomas Munn
________________________________

**Comment by favonia** [comment]
Thanks for your feedback. However, I am unsure how your suggestions could give you a better experience on macOS (compared to Docker for Mac). Anyone can already use Appainer/Singularity or rootless Docker to run the published Docker images. In other words, the updater, as it is now, can (1) run securely on Linux, with or without containers, and (2) run securely on any OS where Docker is supported. The only thing it cannot do is run securely on a non-Linux OS without containers (or some form of virtualization). Therefore, I am afraid many of your suggestions do not reduce the overhead of running this updater in macOS: seccomp is Linux-specific, and all other suggestions still have the container overhead.

Perhaps you meant we should use alternative protections (e.g., rootless modes, seccomp profiles, etc.) and delete the Linux-specific code from the updater. I am hesitant to do so because many people are still running Docker with root privileges, and I expect this updater to be treated the same way. I think the container overhead is worth it if it will make the typical default operation much more secure.

PS: seccomp is on my plan, but it never became my priority because Linux capabilities already gate many system calls. You are welcome to make a pull request to contribute a seccomp security profile.

PPS: Running as a non-root user is just part of the protection: Appainer/Singularity, by default, will mount /tmp and your home directory, as their design philosophy favors integration over isolation, but the updater should not be integrated with anything.

**Comment by symgryph** [comment]
In the context of the Mac we could be looking at using sandbox model ensuring sandboxing is enabled. I'm not sure how to do it but I do know that you can enable use of the sandbox.

Sincerely

Thomas Munn
________________________________

**Comment by favonia** [comment]
As I said, the problem is that I don't have the time/energy to maintain the per-OS security defense:

> The alternative is to implement proper security protections for different operating systems, but I would not have enough time to check the correctness of them (even if just for macOS).

**Comment by favonia** [comment]
@symgryph Now the source code should run in Mac OS without any changes. It simply ignores Linux capabilities and only changes only the user ID and group ID. I hope this satisfies your need. Sorry about the long delay before delivering this (obvious) solution.
