### ISSUE TITLE
ipv6 finds machine address not external address

### ISSUE THREAD

**Issue by technerdmike** [favonia/cloudflare-ddns#197]
I've tried both the bridge and host methods. Both only pull the machine ipv6 address. Thanks

I should also mention that I set it up in portainer.

**Comment by technerdmike** [comment]
With further testing, it looks like something wrong with the Ubuntu 22.04 server settings as the commands from cloudflare and ipify work on other devices and find the correct ipv6 address.

**Comment by favonia** [comment]
It's challenging to debug the program without seeing the configuration. Could you possibly provide it (but remember to edit out your API token and domains)? The `ipify` and `cloudflare` providers should only give you external IPs. If you are using the `local` provider, as its name suggests, it can only detect your "machine address", which I assume to be the local address. In any case, I need more information to help you.

**Comment by favonia** [comment]
@technerdmike Hi, did you get a chance to look at this? I need to see at least the configuration you used. On the machines where public IPv6 addresses could not be fetched, does the output of `curl https://api6.ipify.org` give you the correct public IPv6 address? (Do not paste the IP on GitHub.) Anyways, I I need more information.

**Comment by technerdmike** [comment]
Hi @favonia, I was on holidays and just got back. I'll send the config soon. The curl gives me the machine ipv6 however, if I try it on a different machine on the same network, it gives me the network ipv6. I suspect I did something on the machine that is causing this error.

**Comment by technerdmike** [comment]
Hi @favonia, I am using your docker image on an Ubuntu 22.04 Server with Portainer as the manager. The only two environmental variables are the CF_API_TOKEN, DOMAINS, and IP6_PROVIDER (currently set to none). I have tried every provider setting. I curled ipify.org on the bare metal and also got the local ipv6 address instead of the public one. I am currently combing the internet to see if there is a loopback setting I have to change to get it to see the public ipv6 address. Right now the container is connected to the host network, but I did a stint trying to get the docker ipv6 settings to work. Therefore, I am seeing if I added settings that are causing this behavior. Thanks for any help.

**Comment by favonia** [comment]
@technerdmike Thanks for sharing this. However I am a bit confused by your description. What confused me most is that, **ipify/Cloudflare can only return your public address, ever.** Whatever address you get from ipify or Cloudflare _is_ your public address used to connect to ipify. Therefore, I do not understand how you knew that the address is not public. Could you elaborate? How did you know that the IPv6 address you got is "wrong"?

Another thing is that, if `curl https://api6.ipify.org` is returning the same address, it means that the updater is irrelevant to the actual problem. I recommend stopping using the updater until you fix the underlying network problem (if there is a problem).

**Comment by favonia** [comment]
@technerdmike I got the idea that you might have confused EUI-48 identifiers (also known as MAC addresses in the context of networking) with IPv6 addresses due to how they are typically written down. A typical EUI-48 identifier looks like
```
01:23:45:67:89:AB
```
and an IPv6 address looks like
```
0123:4567:89AB:CDEF:0123:4567:89AB:CDEF
```
While they both use hexadecimal digits in their usual representations, they are entirely unrelated. `curl https://api6.ipify.org` can never prints out the EUI-48 identifier of your device because that is only known to your local router. No one else can (easily) access that information due to how the internet works.

**Comment by favonia** [comment]
I am closing this GitHub issue because I believe the updater is working as expected. The issue was reported possibly due to (incorrect) recognition of valid IPv6 addresses as EUI-48 identifiers. Feel free to follow up if my assessment is incorrect.

PS: @technerdmike if your server cannot be reached via the IPv6 address, it is more likely that a firewall somewhere (could be your router, your operating system or system service, or anything) is blocking incoming traffic.
