### ISSUE TITLE
Way to differentiate proxied and non proxied domains with docker compose

### ISSUE THREAD

**Issue by nikkopt** [favonia/cloudflare-ddns#227]
I can't seem to find this information in the readme page.
What's the right way to tell the script to proxy the domain foo.bar and not proxy the subdomain test.foo.bar with docker compose?
And while i'm at it. What about the TTL?
Also, if i write *.foo.bar , will the script update every single subdomain?
Thanks in advance.

**Comment by favonia** [comment]
Thank you for opening the issue.

1. The per-domain proxy setting is experimental and it's well-hidden in the setting section. I am planning to replace it with a new system. See #223. Do you like the new language?
2. I am planning to remove the support of per-domain TTL due to the seemingly lack of usage. Do you have a use case? May I know what it is?
3. `*.foo.bar` is a wildcard domain name and it is independent of other names such as `test.foo.bar`. It meant to cover only the domain names that would not otherwise exist. You can use `hasSuffix("foo.bar")` in the current system or `sub(foo.bar)` in the planned new system that would match both `*.foo.bar` and `test.foo.bar`.

As I am still working on the design and the new code, your feedback is important. In the meanwhile, as a workaround, you can run two instances to avoid the template system altogether.

**Comment by nikkopt** [comment]
I'm new to docker and i don't even know how to program. I'm using portainer to import compose files. 
I'm not the best person to be asked if i like the new language because for me everything's the same. I'll just end up using the examples provided.
I asked about the TTL because i saw it mentioned on the readme but didn't see a way to use it with compose. To be honest i don't really need to use it, it was just curiosity.
About the domains, thanks, i get it now. I ended up using to instances like you proposed.
Thanks again.

**Comment by favonia** [comment]
Thank you for your feedback. I should probably explain more about wildcard domains in README. Let me know if something is not working---I made the tool for myself but I also want to make it useful for others. The only downside of multiple instances is that they would eat up more memory and their cache cannot be shared, but if you can afford more memory and/or less efficient network usage, they would work perfectly fine. Again, let me know if something is not working perfectly. I need your feedback to improve this tool further.

**Comment by favonia** [comment]
@nikkopt FYI: #223 was implemented and has been shipped with 1.7.1. It is still "experimental" but I kind of like it (as I managed to implement this feature with a tiny and reasonably efficient parser), so maybe you can depend on it. See README for the documentation. You can use `is(example.org)` to proxy only the domain `example.org` and you can use logical operators to express more complicated logic. (Such as `!is(example.org)` to proxy everything _except_ `example.org`.)

**Comment by nikkopt** [comment]
Tat was fast! At the moment i'm only using one domain. I'll try it as soon as i need it. I took a look at the readme and it looks pretty easy to use. Thanks a bunch!
