### ISSUE TITLE
(delete)

### ISSUE THREAD

**Issue by alpert1** [favonia/cloudflare-ddns#229]
(delete)

**Comment by alpert1** [comment]
Thank you! I discovered it, while looking into the config.go. Maybe you might want to consider including the info about all environment variables in the deployment explanation?

**Comment by favonia** [comment]
@alpert1 I will consider that. I'm hesitant to add more stuff to the deployment section because there's a long explanation within "Schedules and Timeouts" which lists various options. Do you think a pointer like "there are many more options---see X" would help your past self?
![image](https://user-images.githubusercontent.com/1471328/196445117-dbee06de-9915-4bb3-99e1-951327f62413.png)

**Comment by alpert1** [comment]
Oh, it was there all along! The actual issue here was me not realizing that the arrow-shaped bullet points in guithub can be expanded and are not just lists. 🤦‍♂️

Sorry to bother you!

**Comment by favonia** [comment]
FYI: it should be clear now that those items can be expanded.
