### ISSUE TITLE
Multiple domains w/wildcards / API token questions

### ISSUE THREAD

**Issue by truthsword** [favonia/cloudflare-ddns#345]
New to this project, moving from oznu, as I now have a second domain on Cloudflare. 

I want to confirm my understanding with multiple domains, wildcards, and API tokens.

- I have 2 domains with Cloudflare
- Each domain has a wildcard registered as an "A" record (not CNAME)

Is this then correct?
`- DOMAINS=domain1.com,*.domain1.com,domain2.com,*domain2.com`

Also... since I have two domains, it would seem I have two API tokens, one per domain. Is that correct?

The examples I see only show one API token in the environmental variables. Can I use ether API token (domain1 or domain2), or must I run two separate containers? Or is there a better way?

I'm confused here. Thank you for your help!

**Comment by favonia** [comment]
Hi, thanks for using this tool.

1. If you want to disable IPv6 (that is, no `AAAA` records), remember to use `IP6_PROVIDER=none` or replace `DOMAINS` with `IP4_DOMAINS` (either works). Otherwise, it looks great.
2. You can use one token to manage arbitrarily many zones or domains, and you have complete control over its scope. When creating an API token, you can choose "All zones" for "Specific zone" and the tool can then manage all domains with the same token. Check out https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ and pay attention to the third step.
3. Because of the above point, the tool currently can only handle one API token.

Let me know if this solves your problem, especially if it doesn't.

**Comment by truthsword** [comment]
Thank you for this added clarity. I'll spin up this container over the weekend.

**Comment by truthsword** [comment]
All looks good. 
![](https://i.imgur.com/vRAOR54.png)
Thanks for your work here!

**Comment by favonia** [comment]
Glad that it works! @truthsword I wonder if there's something I should add to the documentation to clarify it (for your past self)?

**Comment by truthsword** [comment]
> I wonder if there's something I should add to the documentation to clarify it (for your past self)?

I think I'm good. Disabling IPv6 did not sink in initially (presently limiting only to IP4).

I left proxying as "true" even though I have no website associated with these domains. Not sure if that matters. Thanks for asking!

**Comment by favonia** [comment]
@truthsword Got it.

1. For IPv6, it does not hurt to leave IPv6 enabled. You will see messages creating AAAA records or a hint saying you can turn IPv6 off. Nothing will go wrong unless you absolutely do not want AAAA records even if you have IPv6. So, I will leave the documentation unchanged for IPv6.

2. For proxying, see https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/. It sounds like I should update the documentation? Here's what's on Cloudflare:
   > If you need to connect to your origin using a non-HTTP protocol (SSH, FTP, SMTP) or the traffic targets an [unsupported port](https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/) at the origin, either leave your records [unproxied (DNS-only)](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/#dns-only-records).

**Comment by favonia** [comment]
> 2\. Perhaps I should update the documentation?

FYI: the documentation was updated in #346 so that the warning is more visible.
