### ISSUE TITLE
Notification of IP changes and errors

### ISSUE THREAD

**Issue by obstrux** [favonia/cloudflare-ddns#532]
Ex. Email

**Comment by favonia** [comment]
Thanks for the feedback. You can set up [Healthchecks](https://healthchecks.io) and put the ping URL into `HEALTHCHECKS`. This way, you will receive emails when there's an error. If you are looking for something else, please let me know. 🙂

**Comment by alipay404** [comment]
> @alipay404 Thanks for the feedback. You can set up [Healthchecks](https://healthchecks.io) and put the ping URL into `HEALTHCHECKS`. This way, you can receive emails (or SMS messages, etc.) _when there's an error._ If you are looking for something else, please let me know. 🙂

Thanks

**Comment by alipay404** [comment]
> @alipay404 Thanks for the feedback. You can set up [Healthchecks](https://healthchecks.io) and put the ping URL into `HEALTHCHECKS`. This way, you can receive emails (or SMS messages, etc.) _when there's an error._ If you are looking for something else, please let me know. 🙂

How do I get an IP change

**Comment by favonia** [comment]
@alipay404 The current design does not notify you of IP changes because that's not an error. Let me re-open this issue because you seem to be requesting a new feature.

**Comment by favonia** [comment]
@alipay404 Hi, because you are asking for a new feature, I wonder if you could possibly provide more details. In particular, _when_ do you want to receive notifications and what should be the messages? If you have seen this feature in another product, I can take a look. tl;dr: I need more details.

**Comment by favonia** [comment]
@alipay404 I checked GoDNS and they only mentioned "IP changes". Do you also want to get notifications when something's wrong (e.g., when the updater fails to get the public IP)? Also, do you have a preference between webhooks (you specify the URL and the content) and something like [shoutrrr](https://github.com/containrrr/shoutrrr) (which might increase the image size)? It is not difficult to implement any of these but I want to implement it in a way that addresses your need (if I choose to implement it after checking the technical detail). 😀

 @bartclone if you are willing, any input will be helpful to move this issue forward. Thanks!

**Comment by bartclone** [comment]
> @bartclone if you are willing, any input will be helpful to move this issue forward. Thanks!

Sure. A IP change could have effects, that an user wants to be notified of.
So, yes, an interface to a [notification API service] like shoutrr, or [Apprise](https://github.com/caronc/apprise/wiki) / its [API](https://github.com/caronc/apprise-api) would be nice.

**Comment by favonia** [comment]
> A IP change could have effects, that an user wants to be notified of.

Do you want to get notifications when something went wrong (e.g., not being able to get the IP)?

PS: I would like to check how large the images would be after linking shoutrrr.

**Comment by bartclone** [comment]
> > A IP change could have effects, that an user wants to be notified of.
> 
> @bartclone Thanks for the feedback. Do you want to get notifications when something went wrong (e.g., not being able to get the IP)?
> 
> PS: I would like to check how large the images would be after linking shoutrrr.

Maybe introduce a [debug level](https://sematext.com/blog/logging-levels/) 1-6, to control which messages are sent out?
Like 
- not getting an IP : level Fatal
- which IP is used: Info

**Comment by favonia** [comment]
@bartclone All logs already have levels. However, the logs are only optimized for the terminal view and imperfect for notifications. (E.g., some messages are intentionally split into multiple lines.) To have the best UI/UX, I believe one would have to manually adjust messages for different targets. I also want a clean configuration interface where every option should ideally have a reasonable meaning independent of other options. I'm worried that it is not immediately clear whether the log level should also affect the messages sent to Healthchecks and the terminal (and maybe replace the option `QUIET`). I'm hoping to avoid non-trivial interactions between options.

Anyways, to confirm, I believe you don't expect to receive notifications other than (1) IP changes and (2) all kinds of "errors". Is that correct? It might take me a while to go through all the errors the updater is reporting right now, but technically I don't think supporting this is difficult other than the size bloat due to the shoutrrr library.

**Comment by favonia** [comment]
@bartclone Sorry for the slow progress. Do you think you will ever need to notify multiple targets?

**Comment by favonia** [comment]
@alipay404 @bartclone I played with `shoutrrr` a bit and it seems to be a bit large (with respect to the current tiny updater). I'd love to keep the updater tiny but could be convinced otherwise. I wonder if you are already using a popular notification system, for example, [gotify](https://gotify.net/), or online services that support notification redirection, such as [novu](https://novu.co/), [courier](https://www.courier.com/pricing/), [magicbell](https://www.magicbell.com/pricing), or something like that?

**Comment by bartclone** [comment]
Sorry for the late reply, holidays kicked in ;).
I myself use PushOver, but then again: so many choices, therefor I proposed the broader solution (lots of services to choose). 
These days harddiskspace is cheap - although 4Mb is ofcourse large when for example used in IoT/edge.

**Comment by favonia** [comment]
@bartclone I admit that it's more like an intellectual exercise for me to create the smallest but maintainable DDNS updater with all the features I like. This project was my way of learning Go. I'd like to think through the alternatives---last time I managed to save some bits and improve usability by handcrafting [my own parser.](https://github.com/favonia/cloudflare-ddns/blob/main/internal/domainexp/parser.go)

I suppose you don't need the updater to notify multiple places. Is that correct?

**Comment by favonia** [comment]
@bartclone I think I'm about to give up finding alternative designs. There are two things to decide and one major difficulty to worry about. The two things are:

1. The environment variable should be `SHOUTRRR`, right?
2. The exact messages to send out---in particular, should the tool send out `IP changed to X from Y` instead of just `IP changed to X`? Is the additional information useful? The tricky part of implementing this is that the original DNS records could be a mess and I'd like to know whether it's worthwhile to come up with a good description for each case.

The major difficulty is that this feature would take me a while (if I want to add all the test cases and whatnot).

**Comment by bartclone** [comment]
Or maybe just use the ability to a use the API of [Apprise](https://github.com/caronc/apprise-api). 
I took a quick look but Shoutrrr does not seem to provide that?
Apprise also provides a built-in Configuration Manager ...
 
Using an external service like Apprise (or maybe Shoutrrr?) would limit your codebase.
Ofcourse still needed to define how to call the service, for example running in a another container. That would require URL, API (key for the service), etc etc

On loglevels, see https://sematext.com/blog/logging-levels/
It's always a question what severity/level (and to what extend) a specific event has :). Let's find out.
- An IP-change itself could be regarded as: info
- An IP-update fails: error
- Services cannot be reached: fatal

**Comment by favonia** [comment]
@bartclone Thank you!

1. I feel running another server instead of including a library might be a bit too much for the end user. :sweat_smile:
2. No, I'm not talking about logging levels. I am talking about the actual messages to be sent. There's already a logging system for outputting messages in Docker. However, it is not optimal to recycle logging (recording what the updater is doing) for notifications (telling users about something they may have to act on soon). There are important things that should not be notifications (e.g., whether QUIET mode is used). Logging and notification serve different purposes and messages should be tailored. The question here is whether the old IP should be mentioned.

**Comment by favonia** [comment]
Unfortunately it is difficult for me to spend enough time on this issue. PRs are welcome. It is not inherently hard to integrate shoutrrr, just lots of testing and checking. I will leave this open for now.

**Comment by favonia** [comment]
Current plan: These will be notified:

- Starting of the program
- Configuration errors
- Use of deprecated settings
- IP detection error (every time!)
- IP changes
- Successful detection of the same IP after failures
- Failures to update DNS records
- Exiting of the program

These will not be notified:

- Failure to ping monitors

**Comment by favonia** [comment]
@bartclone In case you are still interested, I wonder if you want the updater to set the _title_ of a Pushover message or you to specify the title by yourself? I'm asking this because it seems the title set by the updater will overwrite what's set by the user (not completely sure).

**Comment by favonia** [comment]
@bartclone Progress report: I have implemented experimental support of shoutrrr but right now it has bugs: strangely, messages cannot be sent to pushover. If you feel adventurous, you could use `SHOUTRRR=<shoutrrr url>` with the Docker tag `edge`. I am still debugging it.

**Comment by favonia** [comment]
Update: the bug was fixed! However, only the failure to detect IP addresses or update DNS records is currently notified. I'm working on other errors.

**Comment by favonia** [comment]
This is done now, pending updates on documentation.

**Comment by favonia** [comment]
:tada: The new feature was released with 1.12.0. Please try it out!
