### ISSUE TITLE
Sometimes the updater sends the message "OK" when failing

### ISSUE THREAD

**Issue by JvdMaat** [favonia/cloudflare-ddns#648]
Following up on #615, I just had the following error in the docker logs:
```
🔔 Successfully pinged Uptime Kuma
⏰ Checking the IP addresses in about 5m0s . . .
😞 Failed to send HTTP(S) request to "https://1.1.1.1/cdn-cgi/trace": context deadline exceeded
😞 Failed to detect the IPv4 address
🔔 Successfully pinged Uptime Kuma
⏰ Checking the IP addresses in about 4m55s . . .
🌐 Detected the IPv4 address: 71.x.y.86
🤷 The A records of "ddns.domain.com" are already up to date
🔔 Successfully pinged Uptime Kuma
⏰ Checking the IP addresses in about 5m0s . . .
```
Which is totally fine (I rebooted my router, so the container was running, but it couldn't reach the internet for that one interval).
However this is what Uptime Kuma showed:
![image](https://github.com/favonia/cloudflare-ddns/assets/90044149/828f814c-b1b3-4577-84b5-fe4db2e7504a)
(So it sent an OK instead of the actual issue of "context deadline exceeded" (or request timed out, or whatever makes sense as error message))

**Comment by favonia** [comment]
@JvdMaat Sorry that we didn't completely fix the problem. Can I double check that you are using 1.11.0?

**Comment by favonia** [comment]
@JvdMaat Hi, I wonder how annoying this bug is to you? I'm in the middle of (extremely slowly) adding `shoutrrr` (see https://github.com/favonia/cloudflare-ddns/issues/632) and I prefer not to release a version with lots of non-functional code. However, the non-working code does not affect other functionalities and nothing prevents me from releasing a bugfix, either.

**Comment by JvdMaat** [comment]
This bug has little to no impact on me. Just a cleanup of missing error messages as far as I'm concerned. File it with nice to have.
