### ISSUE TITLE
Just some basic question

### ISSUE THREAD

**Issue by xd003** [favonia/cloudflare-ddns#654]
Hello, thanks for making this great tool. I am not much into networking and not sure if i understand all the technicalities correctly. I have a dynamic IP and just wanted to use this tool to update my dns records for Adguard Home domain. As the default schedule to recheck and update the DNS records is set to 5 min, doesn't this mean that when my dynamic ip changes, my domain still pointing to the older IP would be down for 5 minutes until it gets updated which would eventually mean my internet would be down for 5 mins every time ip is changed being connected to the Adguard DOH
is there any way to avoid it ?

**Comment by favonia** [comment]
Hi, GitHub is designed to discuss potential issues that may require changes to the tool itself (e.g., bugs, unexpected errors or messages, confusing documentation, etc.). and I believe your question is about generic DDNS, not this tool. You might be able to get better help on platforms such as Reddit, especially if you believe Adguard is involved. Anyway, the short answer is yes, your domain will be "down" for a while. However, there are some clarifications I want to make:

1.  The DNS records are cached in all layers---remote DNS servers (including Adguard ones), possible local DNS servers in your operating systems, your applications (e.g., browsers), etc. It will be extremely insufficient if every domain is rechecked every time against the original (authoritative) name server. So, even if your Cloudflare records are kept up to date instantly, it will still take time for other people to pick up your new IPs. This is strongly influenced by "TTL" value of a DNS record, and different implementations may have their own policies in deciding when to re-query the domain.
2. There's no reliable way to know that your IPs have changed unless your router or ISP supports a notification or callback mechanism. The updater here is a generic solution that uses network connections themselves to detect IP changes. By design, it does not depend on any special mechanism but there will be a delay. This applies to any generic DDNS updater.
3. Adguard is probably not relevant here, except that their DNS servers will implement their own policies about when to refresh cached DNS records, just like everyone else.
4. Finally, if you cannot tolerate minutes of down times due to IP changes, I strongly recommend buying static IPs. Contact your ISPs or hosting services for such options. Once you have static IPs, you do not need this tool or any DDNS updater to update your IPs, and there will be no delay.

Hope these help.

**Comment by xd003** [comment]
Thank you so much for the detailed explanation, that's really a good read
