### ISSUE TITLE
Could not verify the Cloudflare API token: context deadline exceeded

### ISSUE THREAD

**Issue by Niaw** [favonia/cloudflare-ddns#813]
Hello,

With the last version: Cloudflare DDNS (v1.13.0-0-gd09dc8f)

I have this message:
`Could not verify the Cloudflare API token: HTTP request failed: Get "https://api.cloudflare.com/client/v4/user/tokens/verify": context deadline exceeded`

But when testing in CLI with:
https://developers.cloudflare.com/fundamentals/api/troubleshooting/
`curl "https://api.cloudflare.com/client/v4/user/tokens/verify" --header "Authorization: Bearer <API_TOKEN>"`

I have:
```
{"result":
{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","status":"active"},
"success":true,
"errors":[],
"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]
}
```

The DDNS is working, nonetheless.

Thanks for your work and your help.

**Comment by favonia** [comment]
@Niaw Thank you for the report. The message means it failed to verify the token **in one second** (hard-coded [here](https://github.com/favonia/cloudflare-ddns/blob/9ccf9dfbf3d3ce0211c5af8c5345e809b1d7d266/internal/api/cloudflare.go#L98)) and you can safely ignore the message. I will release a new version with better error messages.

FYI: The background story is that the tool used to bail out quickly when the verification fails, but that could due to temporary network failures. The new one (introduced in #790) will keep trying unless it's 100% sure that the token is bad. I was worried that the repeated verification will take too much time, and thus imposed a one-second limit on the verification, which led to the error message you see.

**Comment by favonia** [comment]
@Niaw FYI: in the new version, there will be no error messages when the quick token checking time outs.

**Comment by Niaw** [comment]
Great! Thank you for the work and the explanation.
