### ISSUE TITLE
Cache disable

### ISSUE THREAD

**Issue by tritri301** [favonia/cloudflare-ddns#821]
Hello, I recently started using the DDNS script and noticed it's caching API requests to Cloudflare. I simulated an IP address change, but after 20 minutes, my DNS record hadn't updated because all requests were fetched from the cache. I had to reboot the container to finally update my record. Can this caching feature be disabled?

Thanks!

**Comment by favonia** [comment]
You can set `CACHE_EXPIRATION` to `1s` so that the caching immediately expires. This option is further explained under the section "⏳ Schedules, triggers, and timeouts". May I know if you have actual uses other than testing the tool? Otherwise, I encourage you to keep the default value to reduce the network traffic.

Just to be clear, when your actual IP changes, your records will be updated _immediately_.

**Comment by favonia** [comment]
BTW, you are not the first one trying to test the tool this way, so maybe I should add a FAQ section in README about this. Again, there's a difference between a change in your actual IP (which will trigger the update) and a change in your Cloudflare records (which should not happen in normal situations).

**Comment by tritri301** [comment]
Oh I see! I'm sorry I misunderstood how this works, but it does make a lot of sense. Maybe an FAQ could indeed help others like me :)

Thanks you!
