### ISSUE TITLE
Feature Request: Update Cloudflare DNS Record Comment to Include Timestamp

### ISSUE THREAD

**Issue by trjohnson19** [favonia/cloudflare-ddns#847]
Hello,

First of all, thanks for the great product, it's been working fabulously. I was wondering if it might be possible to add an environmental variable similar to `RECORD_COMMENT` that would include a date/time/timezone stamp in the DNS record comment. Bonus points if it is a [configurable timestamp](https://go.dev/play/p/Lm018dbTxQB), but UTC ISO 8601 / RFC 3339 is more than sufficient.

e.g. something of the format `[YYYY-MM-DDThh:mm:ssZ] Created by cloudflare-ddns`... or whatever format suits your fancy @favonia.

**Comment by favonia** [comment]
@trjohnson19 Thanks for the suggestion. I think the difficulty is really to have a clean UI to configure the comments. On the other hand, for your use case, is it sufficient to use shoutrrr to tell you the change events? May I know the motivation about the timestamps? Knowing the motivations helps me a lot.

**Comment by trjohnson19** [comment]
The use case is mostly similar to that of using shoutrrr for notifications. I’ve just [not yet gotten around to](https://github.com/trjohnson19/docker-stack/commit/a69bc0f77b3db80060720f6265635fa0ef883477) setting up shoutrrr.

Basically, I had the issue where I was away from my house and my docker went down, so I checked Cloudflare to see the latest DDNS entry. It would have been quite clear at that point if I had seen the latest update hadn’t been for ~3–4 days that my stack had gone down.

**Comment by favonia** [comment]
@trjohnson19 Got it. What you need is probably a [dead man's switch.](https://en.wikipedia.org/wiki/Dead_man%27s_switch) One possible choice is https://healthchecks.io/. The idea is that the DDNS will constantly ping the website "hey I'm alive!" if it's working fine. When the website does not hear the "hey I'm alive!" for some time, it can notify you. Please read the section "Logging, Healthchecks, Uptime Kuma, and shoutrrr" about how to configure the feature.

If this seems to address your need perfectly, I might close this issue because it might not be easy to design an UI to configure the feature you requested.

**Comment by trjohnson19** [comment]
That's fair, I can understand not wanting to add unneeded complexity when other options exist. Thanks for the recommendations!

Closing.

**Comment by favonia** [comment]
@trjohnson19 Well, I actually think the Healthchecks might address your need better! Let me know if it doesn't address all your need so that we can brainstorm something.
