### ISSUE TITLE
The name "WAF lists"

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#896]
@Gamerou Sorry to bother you again, but I would like to hear your feedback on this: I'm still not 100% satisfied with the name "WAF lists". I realized that these lists can also be used in [Cloudflare Rules](https://developers.cloudflare.com/rules/). On the other hands, there are [similar but different lists for Zero Trust gateways](https://developers.cloudflare.com/cloudflare-one/policies/gateway/lists/) which can also contain IP addresses. I have been trying all kinds of different names:

1. `LISTS`: this is probably too generic.
2. `IP_LISTS`: this is more specific, but a Zero Trust gateway list can also contain IPs.
3. `WAF_LISTS`, meaning "lists for WAF": the lists can actually used in rule expressions outside WAF. The core product is [Cloudflare's Ruleset Engine](https://developers.cloudflare.com/ruleset-engine/)---any other product using it can use these lists.
4. `RULES_LISTS`: this is technically accurate, but the name looks like "lists of rules".
5. `RULESET_LISTS`: this looks like lists of rule sets; also, even though `RULESET` is a very precise name for [Cloudflare's Ruleset Engine](https://developers.cloudflare.com/ruleset-engine/), people who don't know the product might have zero ideas what `RULESET` refers to.

In the end `WAF_LISTS` still looks the best choice, but I'm not 100% happy. I wonder if you (who will be likely one of the earliest users) have any suggestions or comments on this.

**Comment by Gamerou** [comment]
No problem at all! Naming is crucial, so it's worth getting it right. Here's my take on it:

`WAF_LISTS` is clear and makes a direct connection to a known feature, but as you noted, it doesn't fully capture the broader use case. Nevertheless, I would advocate continuing to use the name.

Nevertheless, I have thought about alternatives:

`RULES_LISTS`: Although this could be misinterpreted as “lists of rules”, it's still a good candidate because it directly links the lists to their use in rules. If you're concerned about the potential confusion, adding documentation to clarify might help.

`POLICY_LISTS`: This name suggests that the lists are part of a broader policy or rule set that could cover WAF as well as other use cases like Zero Trust Gateways. It is broad enough to cover different use cases and still be specific. However, not everyone might understand what is meant right away.

`SECURITY_LISTS`: This name is broader and emphasizes that these lists are used in security contexts, be it for WAF, rules or zero trust, but I think it is too general.

`POLICY_LISTS` is perhaps the most versatile and clearest alternative among these names. It makes it clear that these lists are used in broader security policies, not just for WAF or rules. But I'm still not convinced and would stick with `WAF_LISTS`.

**Comment by favonia** [comment]
@Gamerou Thanks. I should clarify that the lists _cannot_ be used in Zero Trust Gateways or Cloudflare Access. Confusingly, [they have their own lists](https://developers.cloudflare.com/cloudflare-one/policies/gateway/lists/) that can also contain IP addresses, but the two kinds of lists are different.

**Comment by favonia** [comment]
Closing this issue because there is a clear consensus: don't change the current design!
